### ISSUE TITLE
Set monetary expectations and boundaries

### ISSUE THREAD

**Issue by simulaman** [simulaman/EliseAndSteve#1]
As a committed partner, I would like us to create personal budgets, review these budgets with each other, and then based on these budgets set monetary expectations and boundaries for the relationship so we can plan and enjoy wooing ❤️ activities with greater confidence.

**Comment by eaxelrad** [comment]
That is a good idea. We should set a time slot.

**Comment by eaxelrad** [comment]
You have mentioned the expense, but I don't yet have a feel for your constraints. We need to set a time slot for sitting with our budgets together.
