### ISSUE TITLE
Discussion of stress management approaches during  Transport and Storage of Inherited items

### ISSUE THREAD

**Issue by simulaman** [simulaman/EliseAndSteve#2]

**Comment by eaxelrad** [comment]
Thank you for working with me on our plans for next week. This is a time with much potentially stressful interaction with family.  It would be nice to sit and talk about expectations, ways we can signal each other for requests for support or check in, how to handle stressfull moments, and such, even while we have family around.

**Comment by eaxelrad** [comment]
We let this one drop but it is OBE now. Still worth a discussion, though.

**Comment by simulaman** [comment]
We did pretty well.

**Comment by eaxelrad** [comment]
We did well, except around my family. I would still benefit from this discussion.

**Comment by eaxelrad** [comment]
I would still benefit from this discussion. We are dropping items.

**Comment by simulaman** [comment]
The dove flies at midnight... oh wait... I have a question about Catlett, with a hand on shoulder if possible.
