### ISSUE TITLE
Travel Plans, Toronto and Jersey

### ISSUE THREAD

**Issue by simulaman** [simulaman/EliseAndSteve#3]
Plan to go to NJ and Toronto, meet family, and retrieve furniture.

**Comment by eaxelrad** [comment]
I just went to UHaul and learned that they have a 3 day rental from Toronto to Alexandria for over $1000 but a cargo trailer in the $200-$300 range. We could drive to NJ, keep the car and drive back.

**Comment by eaxelrad** [comment]
Weather could be scary crossing through lake effect snow country but you could see Niagara Falls.

**Comment by eaxelrad** [comment]
Cons: Many possible stresses on our relationship. Pros: Efficiency and one heck of an adventure.

**Comment by simulaman** [comment]
A test to see if email reply posts to the issue

**Comment by simulaman** [comment]
The trailer is much more affordable.  Do you know anyone from whom we could borrow a pick-up which could pull said trailer?

**Comment by eaxelrad** [comment]
Yes

On Dec 3, 2017 1:38 PM, "simulaman" <notifications@github.com> wrote:

A test to see if email reply posts to the issue

Sent from my iPhone

> On Dec 3, 2017, at 1:30 PM, eaxelrad <notifications@github.com> wrote:
>
> I just went to UHaul and learned that they have a 3 day rental from
Toronto to Alexandria for over $1000 but a cargo trailer in the $200-$300
range. We could drive to NJ, keep the car and drive back.
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/simulaman/EliseAndSteve/issues/3#issuecomment-348804109>,
or mute the thread

**Comment by simulaman** [comment]
If we could borrow a pick-up then we could:
1) Take a car (kids) and the pick-up (me and you) to NJ on the 23.
2) Kids return in the car, we continue to Toronto in the pick-up.
3) We return from Toronto in the pick-up towing the trailer

**Comment by eaxelrad** [comment]
My "yes" was about your ability to post, not about borrowing a pickup

**Comment by eaxelrad** [comment]
But the uhaul site said I could toe a trailer with my Honda if it was small enough. I'd have to get a hitch and figure out how to haul a trailer through snow mountains and across blizzardy bridges though.

**Comment by eaxelrad** [comment]
Flights from NJ, Hotel, rental car, UHaul booked!
