### ISSUE TITLE
Enjoy Culture

### ISSUE THREAD

**Issue by simulaman** [simulaman/EliseAndSteve#4]
For the sake of enjoying culture together, I would like to plan a trip to an art gallery or concert (or both)
--

**Comment by eaxelrad** [comment]
Visit an IMAX theater and see fish.

**Comment by eaxelrad** [comment]
Visit a planetarium for laser Floyd

**Comment by eaxelrad** [comment]
https://www.imax.com/content/imax-difference

**Comment by eaxelrad** [comment]
Star Wars on IMAX. https://www.imax.com/movies/star-wars-last-jedi

**Comment by eaxelrad** [comment]
I am so glad we got to your supervisor's concert and to the Vermeer exhibit. Thank you for watching Hidden Fortress and Star Wars with me too!
