### ISSUE TITLE
 introducing you to my friends

### ISSUE THREAD

**Issue by simulaman** [simulaman/EliseAndSteve#5]
For connecting you to people in my life, I would like to set up an event where you could meet my friends

**Comment by eaxelrad** [comment]
For connecting you to people in my life, I would like to set up an event where you could meet my friends

**Comment by eaxelrad** [comment]
Working on Vermeer exhibit plan

**Comment by eaxelrad** [comment]
Thank you for all the time together with you meeting my friends. They really like you.

**Comment by eaxelrad** [comment]
We will see Ted and Linda in Toronto on the night of the 28th.

**Comment by simulaman** [comment]
And that will just leave Uhrica (sp)

**Comment by eaxelrad** [comment]
Yes, we might see Ulrike at Harriet's New Year's party.
