### ISSUE TITLE
Creative Time

### ISSUE THREAD

**Issue by simulaman** [simulaman/EliseAndSteve#7]
For quiet intimacy and creative development, I would like to spend time together working on separate creative projects

**Comment by eaxelrad** [comment]
I enjoyed working with you on the weekend of the 9th. I would love to do this again.

**Comment by eaxelrad** [comment]
I am really struggling to move projects of mine forward. Time together like this would help greatly.

**Comment by eaxelrad** [comment]
It was good to work at Tobaccology.
